spring.datasource.url: localhost

spring.datasource.username: sergey
spring.datasource.password: test
spring.jpa.show-sql: true
spring.liquibase.enabled: true

mail:
  protocol: smtp
  smtpHost: smtp.mail.ru
  smtpPort: 465
  smtpSslEnable: true
  smtpAuth: true
  debug: false
  login: test
  password: test

head:
  information:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 111 111-11-11
    email: mail@mail.ru
    copyright: Дмитрий Сергеев
    copyrightFrom: 2005

captcha.lifetime: 1
